/*==================================================================================================
*   Project              : RTD AUTOSAR 4.4
*   Platform             : CORTEXM
*   Peripheral           : FLEXCAN
*   Dependencies         : 
*
*   Autosar Version      : 4.4.0
*   Autosar Revision     : ASR_REL_4_4_REV_0000
*   Autosar Conf.Variant :
*   SW Version           : 1.0.0
*   Build Version        : S32K1_RTD_1_0_0_D2108_ASR_REL_4_4_REV_0000_20210810
*
*   (c) Copyright 2020-2021 NXP Semiconductors
*   All Rights Reserved.
*
*   NXP Confidential. This software is owned or controlled by NXP and may only be
*   used strictly in accordance with the applicable license terms. By expressly
*   accepting such terms or by downloading, installing, activating and/or otherwise
*   using the software, you are agreeing that you have read, and that you agree to
*   comply with and are bound by, such license terms. If you do not agree to be
*   bound by the applicable license terms, then you may not retain, install,
*   activate or otherwise use the software.
==================================================================================================*/
/***********************************************************************************************************************
 * This file was generated by the S32 Configuration Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Configuration Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef FLEXCAN_IP_SA_BOARD_INITPERIPHERALS_PBCFG_H
#define FLEXCAN_IP_SA_BOARD_INITPERIPHERALS_PBCFG_H

/**
*   @file FlexCAN_IP_PBcfg.h
*
*   @addtogroup FlexCAN
*   @{
*/

#ifdef __cplusplus
extern "C"{
#endif

/*==================================================================================================
*                                        INCLUDE FILES
* 1) system and project includes
* 2) needed interfaces from external units
* 3) internal and external interfaces from this unit
==================================================================================================*/

/*==================================================================================================
*                              SOURCE FILE VERSION INFORMATION
==================================================================================================*/
/*
* @file           FlexCAN_Ip_Sa_BOARD_InitPeripherals_PBcfg.h
*/
#define FLEXCAN_IP_SA_VENDOR_ID_BOARD_INITPERIPHERALS_PBCFG_H                     43
#define FLEXCAN_IP_SA_AR_RELEASE_MAJOR_VERSION_BOARD_INITPERIPHERALS_PBCFG_H      4
#define FLEXCAN_IP_SA_AR_RELEASE_MINOR_VERSION_BOARD_INITPERIPHERALS_PBCFG_H      4
#define FLEXCAN_IP_SA_AR_RELEASE_REVISION_VERSION_BOARD_INITPERIPHERALS_PBCFG_H   0
#define FLEXCAN_IP_SA_SW_MAJOR_VERSION_BOARD_INITPERIPHERALS_PBCFG_H              1
#define FLEXCAN_IP_SA_SW_MINOR_VERSION_BOARD_INITPERIPHERALS_PBCFG_H              0
#define FLEXCAN_IP_SA_SW_PATCH_VERSION_BOARD_INITPERIPHERALS_PBCFG_H              0
/*==================================================================================================
*                                     FILE VERSION CHECKS
==================================================================================================*/

/*==================================================================================================
*                                          CONSTANTS
==================================================================================================*/

/*==================================================================================================
*                                      DEFINES AND MACROS
==================================================================================================*/
#define FLEXCAN_IP_PB_CFG \
extern const Flexcan_Ip_ConfigType FlexCAN_Config0; 
#define INST_FLEXCAN_0 0U
#define FLEXCAN_IP_STATE_PB_CFG \
extern Flexcan_Ip_StateType FlexCAN_State0; 

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* FLEXCAN_IP_SA_BOARD_INITPERIPHERALS_PBCFG_H */

